site_name: fennecpixels
site_url: https://fennecpixels.com

theme:
    name: 'material'
    logo: assets/icon.png
    favicon: assets/icon.png
    features: 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

    palette:
    
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


# COpyrigt
copyright: Copyright &copy; 2024 fennecpixels unless otherwise stated.

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - blog
  - redirects:
    redirect_maps:
      'Fracture.md': 'https://wiki.fennecpixels.com'

extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/fennecpixels.com
      name: fennecpixels.com on Bluesky
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/fennecpixels
      name: fennecpixels on Instagram
    - icon: fontawesome/solid/house
      link: https://toyhou.se/fennecpixels
      name: fennecpixels on Toyhouse
    - icon: fontawesome/brands/github
      link: https://github.com/fennecpixels
      name: fennecpixels on GitHub
    - icon: material/email
      link: mailto:contact@fennecpixels.com
      name: Email me - contact ( at ) fennecpixels.com
    



extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
extra_css:
  - stylesheets/extra.css
